lottery/config/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('home.urls', namespace='home')),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^games/', include('games.urls', namespace='games')),
    url(r'^partecipation/', include('partecipation.urls', namespace='partecipation')),
    url(r'^registration/', include('registration.urls', namespace='registration')),
    url(r'^admin/', include(admin.site.urls)),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lottery/games/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
    url(r'^', views.available_games_list, name='available_games_list'),
]

lottery/home/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^Alpha$', views.Alpha, name='Alpha'),
    url(r'^timeleft$', views.index, name='index'),

]

lottery/partecipation/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
    url(r'^$', views.partecipation, name='partecipation'),
    url(r'(?P<game_id>[0-9]+)/$', views.partecipation, name='partecipation'),
    url(r'confirmation/$', views.confirmation, name='confirmation'),
]

lottery/registration/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
    url(r'^', views.registration, name='registration'),
]

lottery/games/models.py
from random import randint

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db.models.aggregates import Count
from django.utils.translation import gettext_lazy as _
from . import helpers

# Create your models here.
class GameManager(models.Manager):
    use_for_related_fields = True


    def available_games(self, user, **kwargs):
        return self.exclude(winner__isnull=False).exclude(partecipants=user).filter(date__gt=timezone.now())

    def games_to_draw(self, **kwargs):
        return self.filter(winner__isnull=True).filter(date__lt=timezone.now())

class Game(models.Model):
    name = models.CharField(max_length=100)
    prize = models.CharField(max_length=100)
    partecipants = models.ManyToManyField(User, through='partecipation.Partecipation', related_name='game_partecipant')
    date = models.DateTimeField(default=helpers.default_date())

    objects = GameManager()


    def clean(self):
        if timezone.now() > self.date:
            raise ValidationError('Game date cannot be in the past.')

    def draw_winners(self):
        for past_game in Game.objects.games_to_draw():
            count = past_game.partecipants.aggregate(count=Count('id'))['count']
            if count:
                random_index = randint(0, count - 1)
                winner = Winner(game=past_game, user=past_game.partecipants.all()[random_index])
                winner.save()

    def __unicode__(self):
        return self.name

class Winner(models.Model):
    game = models.OneToOneField(Game)
    user = models.ForeignKey(User)

class Alpab(models.Model):
    import datetime
    charr = models.CharField(max_length=10)
    date =models.DateField(_("Date"),default=datetime.date.today)

lottery/partecipation/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

from games.models import Game

# Create your models here.
class Partecipation(models.Model):
    user = models.ForeignKey(User)
    game = models.ForeignKey(Game)

    def __unicode__(self):
        return '{} partecipating {}'.format(self.user.username, self.game.name)

    class Meta:
        unique_together = ('user', 'game')

lottery/partecipation/forms.py
from django import forms

from games.models import Game
from .models import Partecipation

class PartecipationForm(forms.ModelForm):
    game = forms.ModelChoiceField(queryset=None)

    def __init__(self, user, *args, **kwargs):
        super(PartecipationForm, self).__init__(*args, **kwargs)
        if user:
            self.fields['game'].queryset = Game.objects.available_games(user)

    class Meta:
        model = Partecipation
        exclude = ('user',)

lottery/games/views.py
from django.shortcuts import render,render_to_response
from django.contrib.auth.decorators import login_required

from games.models import Game,Alpab

# Create your views here.
@login_required
def available_games_list(request):
	return render(request, 'games/games.html', {
        'available_games': Game.objects.available_games(request.user)
    })

def Alpha(request):
    data = Alpab.objects.all()

    stu = {"Alphad": data}

    return render_to_response("home/home.html",context= stu)

lottery/home/views.py
from django.shortcuts import render,render_to_response
from django.http import HttpResponse
import datetime,time
from games.models import Alpab
# Create your views here.
def home(request):
    #delta = datetime.datetime(0000,00,00 21:00:0) - datetime.datetime.now()
    #print(delta)
    now = datetime.datetime.now()
    html = "<html><body>It is now %s.</body></html>" % now
    ddata = Alpab.objects.all()[::-1]
    data=ddata[:8]
    #data = ddata
    stu = {"Alphad": data,'dated':now}
    print(stu)

    return render(request, 'home.html',context=stu)

def index(request):
    now = datetime.datetime.now()
    html = "<html><body>It is now %s.</body></html>" % now
    return render(request,'countdown.html')

def Alpha(request):
    data = Alpab.objects.all()

    stu = {"Alphad": data}
    print('Hello')

    print(stu)
    return render("home.html",context= data)

def dateDiffInSeconds(date1, date2):
  timedelta = date2 - date1
  return timedelta.days * 24 * 3600 + timedelta.seconds

def daysHoursMinutesSecondsFromSeconds(seconds):
	minutes, seconds = divmod(seconds, 60)
	hours, minutes = divmod(minutes, 60)
	days, hours = divmod(hours, 24)
	return (days, hours, minutes, seconds)

lottery/partecipation/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from .forms import PartecipationForm
from .models import Partecipation
# Create your views here.

@login_required
def partecipation(request, game_id=None):
    if request.method == 'POST':

        partecipation_form = PartecipationForm(data=request.POST, user=request.user)

        if partecipation_form.is_valid():
            partecipation = partecipation_form.save(commit=False)
            partecipation.user = request.user
            partecipation.save()

            return redirect('partecipation:confirmation')
    else:
        partecipation_form = PartecipationForm(initial={'game': game_id }, user=request.user)

    return render(request, 'partecipation/partecipation.html', {
        'partecipation_form': partecipation_form,
        'user_partecipations': Partecipation.objects.filter(user=request.user)
    })

@login_required
def confirmation(request):
    return render(request, 'partecipation/confirmation.html')

lottery/templates/base.html
{% load bootstrap3 %}
{% load staticfiles %}
<script src="{% static '/static/js/app1.js' %}">


</script>

{% bootstrap_css %}

{% bootstrap_messages %}

<html>

<head>
<script type="text/javascript">
         <!--
           // Set the date we're counting down to
//var countDownDate = new Date("Sep 5, 2018 15:37:25").getTime();
        var countDownDate = new Date();
    countDownDate.setHours(21);
    countDownDate.setMinutes(00);
    countDownDate.setSeconds(00);

// Update the count down every 1 second
var x = setInterval(function() {

  // Get todays date and time
  var now = new Date().getTime();

  // Find the distance between now an the count down date
  var distance = countDownDate - now;

  // Time calculations for days, hours, minutes and seconds
  var days = Math.floor(distance / (1000 * 60 * 60 * 24));
  var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
  var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
  var seconds = Math.floor((distance % (1000 * 60)) / 1000);

  // Display the result in the element with id="demo"
  document.getElementById("demo").innerHTML = hours + "h : "
  + minutes + " m : " + seconds + " s ";

  // If the count down is finished, write some text
  if (distance < 0) {
    clearInterval(x);
    document.getElementById("demo").innerHTML = "EXPIRED";
  }
}, 1000);

         //-->
      </script>
    <title>
    	{% block title %}The Lottery{% endblock title %}
    </title>
    {% block stylesheets %}
    	<link rel="stylesheet" type="text/css" href="{% static 'css/lottery.css' %}">
    	<link rel="icon" type="image/png" href="{% static 'favicon.ico'%}">

    {% endblock stylesheets %}

</head>

<body >
    <div class="container">

    	{% block content %} {% endblock content %}


    </div>

</body>


</html>

lottery/templates/countdown.html
<!DOCTYPE HTML>
<html>
<head>
<style>
body{
    text-align: center;
    background: #00ECB9;
  font-family: sans-serif;
  font-weight: 100;
}
h1{
  color: #396;
  font-weight: 100;
  font-size: 40px;
  margin: 40px 0px 20px;
}
 #clockdiv{
    font-family: sans-serif;
    color: #fff;
    display: inline-block;
    font-weight: 100;
    text-align: center;
    font-size: 30px;
}
#clockdiv > div{
    padding: 10px;

    border-radius: 3px;
    background: #00BF96;
    display: inline-block;
}
#clockdiv div > span{
    padding: 15px;
    border-radius: 3px;
    background: #00816A;
    display: inline-block;
}
smalltext{
    padding-top: 5px;
    font-size: 24px;
    color: red;
}
</style>
</head>
<body>
<h1>Countdown Clock</h1>

<p id="demo"></p>
<script>
// Set the date we're counting down to
var countDownDate = new Date("Sep 5, 2018 15:37:25").getTime();

// Update the count down every 1 second
var x = setInterval(function() {

  // Get todays date and time
  var now = new Date().getTime();

  // Find the distance between now an the count down date
  var distance = countDownDate - now;

  // Time calculations for days, hours, minutes and seconds
  var days = Math.floor(distance / (1000 * 60 * 60 * 24));
  var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
  var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
  var seconds = Math.floor((distance % (1000 * 60)) / 1000);

  // Display the result in the element with id="demo"
  document.getElementById("demo").innerHTML = days + "d " + hours + "h "
  + minutes + "m " + seconds + "s ";

  // If the count down is finished, write some text
  if (distance < 0) {
    clearInterval(x);
    document.getElementById("demo").innerHTML = "EXPIRED";
  }
}, 1000);
</script>
<div id="clockdiv">
  <div>
    <span class="days" id="day" ></span>
    <div class="smalltext">Days</div>
  </div>
  <div>
    <span class="hours" id="hour"></span>
    <div class="smalltext">Hours</div>
  </div>
  <div>
    <span class="minutes" id="minute"></span>
    <div class="smalltext">Minutes</div>
  </div>
  <div>
    <span class="seconds" id="second"></span>
    <div class="smalltext">Seconds</div>
  </div>
</div>

</body>
</html>

lottery/templates/games/games.html
{% extends "logged_user_base.html" %}

{% block container_view %}

	<div class="row">
		<div class="col-sm-12">
			<div class="panel panel-default">
			    <div class="panel-heading">Available games</div>
			    <div class="panel-body">
			        <div class="list-group">
			        	{% if available_games %}
							{% for game in available_games %}
								<li class="list-group-item">
									<a href="{% url 'partecipation:partecipation' game.id %}"><h4 class="list-group-item-heading">{{ game.name }}</h4></a>
		    						<p class="list-group-item-text">
		    							The prize will be <strong>{{ game.prize }}</strong>, the extraction will be performed <strong>{{ game.date }}</strong>
		    						</p>
								</li>
							{% endfor %}
						{% else %}
							No games available!
						{% endif %}						
					</div>
			    </div>
			</div>		
		</div>
	</div>

{% endblock container_view %}

lottery/templates/home.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}
	{{ block.super}}
	- Where dreams come true (or not)
{% endblock %}

{% block content %}
    <style>
p {
  text-align: center;
  font-size: 60px;
  margin-top:0px;
}
</style>

 	<!--<div class="jumbotron text-center vertical-align">-->
	<div class ="jumbotron text-center vertical-align">
        <h1> <font color="#a52a2a" <strong>The Royal Sultan السلطان الملكي</strong></font></h1>
        <h3> <strong><font color="blue" <p id="demo"></p> ></font> </strong></h3>
   	    <!--<p>Where dreams come true (or not) Next it'll open at <strong>{{ current_date }}</strong>
       </p>-->
{% if Alphad %}
							{% for al in Alphad %}
								<!--<li class="list-group-item">
                                    <h3>{{ al.date }} = <strong> {{ al.charr }}</strong></h3>

								</li>-->

								<h2><font color="white">{{ al.date }} = <strong> {{ al.charr }}</strong></font> </h2>
							{% endfor %}
						{% else %}
                            Not there
						{% endif %}

	   <!-- <p><a class="btn btn-info" role="button" href="{% url 'django.contrib.auth.views.login' %}">Login</a>
	        <a class="btn btn-primary" role="button" href="{% url 'registration:registration' %}">Register</a></p>-->
        </div>
	<!--</div>-->

{% endblock %}

lottery/templates/logged_user_base.html
{% extends "base.html" %}

{% load bootstrap3 %}

{% block title %}
	{{ block.super}}
	- Welcome {{ user.username }}
{% endblock %}

{% block content %}

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header"><a class="navbar-brand">This is the Lottery</a></div>
		<div class="collapse navbar-collapse">
		    <ul class="nav navbar-nav">
		        <li><a href="{% url 'games:available_games_list' %}">Games</a></li>
		        <li><a href="{% url 'partecipation:partecipation' %}">Partecipations</a></li>
		    </ul>
		    <ul class="nav navbar-nav navbar-right">
		    	<li><a>{% bootstrap_icon "user" %} {{ user.username }}</a>
			    <li><a role="button" href="{% url 'django.contrib.auth.views.logout' %}?next={% url 'home:home' %}">Logout</a>
			</ul>
		</div>
    </div>
</nav>

{% block container_view %}

{% endblock container_view %}

{% endblock content %}

lottery/templates/partecipation/confirmation.html
{% extends "base.html" %}

{% block title %}
You made it!
{% endblock %}

{% block content %}
	<div class="jumbotron text-center vertical-align">
	    <h1>Thanks for partecipating</h1>
	    <p>I hope you will win, seriously</p>
	    <p><a class="btn btn-primary" role="button" href="{% url 'partecipation:partecipation' %}">Go back</a></p>
	</div>
{% endblock %}

lottery/templates/partecipation/partecipation.html
{% extends "logged_user_base.html" %}

{% load bootstrap3 %}

{% block container_view %}

<div class="row">
	<div class="col-sm-12">
		<div class="panel panel-default">
		    <div class="panel-heading">Partecipate</div>
		    <div class="panel-body">
				<form id="partecipation_form" method="post" action="" enctype="multipart/form-data">
					<div class="form-group">
                		{% bootstrap_form partecipation_form %}
					    {% csrf_token %}
					    {% buttons %}
		                    <button type="submit" class="btn btn-primary">
		                        {% bootstrap_icon "star" %} Partecipate
		                    </button>
                		{% endbuttons %}
				    </div>
				</form>
		    </div>
		</div>		
	</div>
</div>

<div class="row">
	<div class="col-sm-12">
		<div class="panel panel-default">
		    <div class="panel-heading">Your partecipations</div>
		    <div class="panel-body">
			    {% if user_partecipations %}
					<div class="list-group">
						{% for partecipation in user_partecipations %}
							<li class="list-group-item">
								<h4 class="list-group-item-heading">{{ partecipation.game.name }}</h4>
	    						<p class="list-group-item-text">
			    					{% if partecipation.game.winner.user %}
										The winner is <strong>{{ partecipation.game.winner.user.username }}</strong>
										{% if partecipation.game.winner.user == user %}
											<strong class="text-green">You won!</strong>
										{% endif %}
									{% else %}
										Partecipations will close on <strong>{{ partecipation.game.date }}</strong>
	    							{% endif %}
	    						</p>
							</li>
						{% endfor %}
					</div>
				{% else %}
					You are not partecipating at any game.
				{% endif %}
		    </div>
		</div>		
	</div>
</div>

{% endblock container_view %}